
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyxofjasoelzxphxcpch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5eG9mamFzb2VsenhwaHhjcGNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNzg3ODgsImV4cCI6MjA1Mzg1NDc4OH0.4jt5nj6HHGjCIt2UpV6ihfhJUelIUAkdSUSph8Q7dHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
